# Dependencies

markdown: kramdown
kramdown: 
  input: GFM
  toc_levels: 1..2
  #parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Zhu Philip's AI Journey"
#dp:               "/assets/profile-pixel.png"
tagline:          ''
description:      ''
url:              https://zphilip.github.io
baseurl:          ''

author:
  name:           'Zhu Tianda'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/zphilip/zphilip.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: zphilip
